### ISSUE TITLE
$content in AbstractBBCode.getParsedTag always <!-- META_CODE_INNER_CONTENT -->

### ISSUE THREAD

**Issue by WebFreak001** [WoltLab/WCF#2236]
`getParsedTag` never receives the actual content of the bbcode block. My custom bbcode for it needs to check if the content contains a character though. Is there any way to actually get the content instead of just that placeholder which gets replaced later?

Calling code: https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/bbcode/HtmlBBCodeParser.class.php#L295

**Comment by dtdesign** [comment]
The actual content is virtually undefined at call time, as the actual output is inconsistent and in-deterministic at that point. Naive string manipulations (including searches) are condemned to fail due to inconsistent content being present, depending on previous actions. This includes actual fragments being moved around at will, following rules specified outside of the scope of the bbcode.

Make use of custom HTML elements if you do require any sort of interaction with the child tree.

**Comment by WebFreak001** [comment]
I've found a workaround: just add an attribute in the settings of the bbcode and set it, so it uses the content of the tag as value. All bbcodes of that block that get created afterwards have an attribute with that value then. (Which is consistent and works well)

**Comment by dtdesign** [comment]
Your approach is just fine in case you're building a `code`-bbcode, in all other cases you're most likely going to send everything downhill. Defining an attribute that sucks up the entire contents will cause that content to be stored inside the attributes, preventing any further processing.
