### ISSUE TITLE
Backend Submit Button, keep in view

### ISSUE THREAD

**Issue by Slind14** [WoltLab/WCF#2262]
It would be great if the submit button would always be visible, no matter how long the site is at which location we are. This eases the use in cases where a lot of changes are required or the user needs to test different settings.

I would recommend putting it next to the "scroll up" icon and using a similar logic, to only display it if the bottom submit button is not in view. Alternatively to display it all the time and remove the bottom submit.
![image](https://cloud.githubusercontent.com/assets/3914677/25559448/b6a53b40-2d3a-11e7-9166-8c73b8dd6997.png)

**Comment by dtdesign** [comment]
It's an interesting idea, but there is currently no simple solution to achieve this without some really quirky CSS changes. I've tried a few different approaches to see how they turn out, but in the end none of them really solved it without causing unwanted side-effects.

Moving the button into the page action bar isn't really a viable option due to the UI/UX decision behind it, that is to provide contextual options to interact with parts of the site. By no means was it ever intended to be used for a regular form submit.

Things get even worse when there is more than one form submit per page, in this case any sort of fixed submit button (forms can also contain multiple buttons!) will get highly ambigious. Consider a top form which has only a "submit" button, with a secondary form below that holds both a "submit" and "preview" button.

Don't get me wrong, I like the overall idea, but I couldn't find a solution that stands strong in non-trivial forms. Feel free to share your thoughts with us in case you got an idea on how to solve this.

**Comment by Slind14** [comment]
I made very small plugin which just adds a bit of css to implement this. So fare I have not had any "major" issues. Yes, there are a few buttons which are above the fold but still being moved, but that is only because I wanted to avoid using javascript and after some time, I'm looking for the button on the bottom right instead of mid content. https://pluginstore.woltlab.com/file/2589-sticky-submit-quality-of-life/

To be honest the source of this idea was somewhat contao related, because it is something I learned to love.
On there they have a form control row on every page which is sticky at the bottom of the page unless the original location is in view:
![image](https://cloud.githubusercontent.com/assets/3914677/26309289/bb09f404-3efc-11e7-985a-fcbbbceb2124.png)
![image](https://cloud.githubusercontent.com/assets/3914677/26309308/cf20c652-3efc-11e7-968e-9bac3d494268.png)

Btw. those additional buttons "Speichern und schließen", "Speichern und neu", Speichern und zurück" are freaking awesome, too. They save so many page views. Something which annoys me, when I create a new element it redirects me to the creation page, but when I edit one, it keeps me on the site, hence I do not have any control over it.

@dtdesign what do you think about shortcuts, e.g. `ctrl/alt + s` to save/submit?

**Comment by TimWolla** [comment]
> @dtdesign what do you think about shortcuts, e.g. ctrl/alt + s to save/submit?

All the forms should have proper accesskeys set: https://developer.mozilla.org/de/docs/Web/HTML/Global_attributes/accesskey
