### ISSUE TITLE
MathUtil::getRandomValue does not use secure randomness if possible

### ISSUE THREAD

**Issue by jens1o** [WoltLab/WCF#2397]
or is there any reason you avoided using `CryptoUtil::randomInt()`(or PasswordUtil ones)?
https://github.com/WoltLab/WCF/blob/5d14d318a8370709e2af8ff44753daca5362081c/wcfsetup/install/files/lib/util/MathUtil.class.php#L22

When both arguments are `null`, it sounds pretty valid to me, but with both values being integers, it does not sound that valid anymore to me.

**Comment by dtdesign** [comment]
Cryptographically secure numbers come at a price and there is absolutely no reason to make use of them, unless you have to. It is the same reason we do use `strpos()` for ASCII-only strings instead of `mb_strpos()`, simply to avoid the overhead of the multi-byte variant when there is absolutely no need.
