### ISSUE TITLE
Reprocessing HTML messages does not account for permissions

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2524]
BBCode permissions are only handled when attempting to save messages, but this is not true for the reprocess API at this point.

**Comment by jens1o** [comment]
this is a breaking change that should be documented, shouldn't it?

**Comment by dtdesign** [comment]
I'm sorry, but how is this a breaking change?

**Comment by jens1o** [comment]
Well, it is a breaking change in this RC phase because now the apps have to respect the new api to work correctly, while in the RC phase the api is per-definition freezed and won't be changed. So I urge you to write a little chapter clarifying what applications need to do and so handle this change as such.

The message reprocessing api has been created before the RC phase, but now the implementations need to be adjusted to the new, fixed behavior.

**Comment by dtdesign** [comment]
The API has not changed at all, I just added something that was missing before.

**Comment by jens1o** [comment]
I don't get why you labeled this a bug then? As far as I understand, third-party apps still need to change their code so the behavior is correctly? For me, that's a breaking change. :(

**Comment by dtdesign** [comment]
That is not the definition of a breaking change ;)
