### ISSUE TITLE
Increasing PHP requirement to PHP 7.0

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#2534]
WoltLab Suite 3.2 will require at least PHP 7.0.

Partially deprecated by #2720.

- [X] ~~Add `declare(strict_types=1);` to all files expect `index.php`, `global.php`,` config.inc.php`, and `app.config.inc.php` and fix type issue after that change.~~
- [X] ~~Use scalar type hints and return type values **in new / final classes only**.~~
- [x] Add php version check to `global.php`.
- [x] Remove workarounds for non-supported PHP versions.
- [X] ~~Run a test against a `libmysqlclient`-build to check how it behaves with scalar type hints.~~
  - [X] ~~If it turns out to be conflicting, add MySQL's native driver to the requirements and include a pre-connection check by [parsing the phpinfo() output](https://github.com/php/php-src/blob/6053987bc27e8dede37f437193a5cad448f99bce/ext/pdo_mysql/tests/mysql_pdo_test.inc#L166).~~
- [X] Update minimal PHP version in `.travis.yml`.

**Comment by LKDevelopment** [comment]
@gravatronics: Just Image 3.2 will be released in First months of 2019. PHP 7.0 will be EOL in 3.12.18 so you require a unsupported Version. Why Not PHP 7.1?
http://php.net/supported-versions.php

**Comment by dtdesign** [comment]
Unfortunately, the supported PHP versions in the major linux distributions are the limiting factor for us. 

* Debian 9 "Stretch" comes with PHP 7.0 and reaches EOL in (est.) 2020 [1]
* Ubuntu 16.04 LTS comes with PHP 7.0 and reaches EOL in April 2021 [2]

I can easily continue this list, and while be agree that using EOL PHP versions is a bad thing, we do encounter outdated systems every day and are simply left without a choice. There are still far too many users that are on PHP 5.5 because they use Ubuntu 14.04 LTS (EOL in April 2019) and it is near impossible to convince these users to move "because everything is working for them".

The point is, PHP 7.1 doesn't offer anything of value for us that would justify increasing the minimum required version, PHP 7.2 is far more important due to the parameter type widening implemented in that version. Essentially, PHP 7.0 offers us a great amount of new features that aid in the development and help us to build a better software, without breaking compatibility with outdated binaries on certain OS.

[1] https://wiki.debian.org/DebianReleases#Production_Releases
[2] https://wiki.ubuntuusers.de/Xenial_Xerus/

**Comment by jens1o** [comment]
Do you also plan to upgrade the MySQL/MariaDB Version? 🎉
