### ISSUE TITLE
Remove `GroupedUserList` caching mechanism in favour of UserProfileRuntimeCache

### ISSUE THREAD

**Issue by jens1o** [WoltLab/WCF#2552]
https://github.com/WoltLab/WCF/blob/81f1ab307e4b6470fd86f5e400a4b9ed40653293/wcfsetup/install/files/lib/system/user/GroupedUserList.class.php#L95-L118

effectivly is the same as the mechanism in UserProfileRuntimeCache, so we should consider rewriting this section to not have two caches playing off each other.

**Comment by dtdesign** [comment]
It does overlap remotely, but the overhead is rather small, because the cache consists of object references and thus is completely shared. On top of that, the `GroupedUserList` isn't a final class and changes to its internal behavior could break compatibility with existing implementations.

Long story short: Yes, could be optimized a bit, but this does not outweight the risk of breaking existing implementations by any means.
