### ISSUE TITLE
Make menus copyable

### ISSUE THREAD

**Issue by jens1o** [WoltLab/WCF#2644]
extracted from https://github.com/WoltLab/WCF/issues/2619#issuecomment-392103351

like in Contao, one menu at the top, one at the bottom, but the content is identical.

**Comment by dtdesign** [comment]
I can barely see a use case for this. Additionally, it would behave very strange when there are menu items present that were created by a package, because they would no longer use the internal identifier and phrases. This creates a situation where seemingly identical menu items behave different both when editing and removing of items, including changes made by packages themselves.
