### ISSUE TITLE
 autocomplete attribute for password fields

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#2694]
see https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands

**Comment by joshuaruesweg** [comment]
Currently, the new password in Account Management does not work as intended. Chrome expects the user, after submitting the form, to be redirected to a different URL so that the user gets the popup "Change password". I wouldn't do that. Nevertheless, I would maintain these attributes, even if they are currently useless, because maybe the feature will be used by other browsers or maintained by Chrome in the future. 

What do you think? 

/cc @dtdesign
