### ISSUE TITLE
Improve a11y / keyboard navigation

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#2713]
Some elements are difficult or impossible to access via keyboard navigation. This includes the following elements:
- [x] box menus, main menu
- [x] nav elements need a label
- [x] drop-downs, drop-down menus
- [x] interactive drop-downs
- [x] datepicker
- [x] 'columnMark' checkboxes
- [x] `<a>` w/o href
- [x] upload-button
- [x] message tab-menu
- [x] overlays (active overlay should limit keyboard navigation to overlay-content)
- [x] reduce usage of complementary `<aside>` tags (change html tag or role to presentation)
- [x] complementary `<aside>` tags need an aria-label
- [x] smileys
- [x] wysiwyg toolbar
- [x] notices
- [x] spoiler bbcode

**Comment by jens1o** [comment]
ref https://community.woltlab.com/thread/261168-größeren-fokus-auf-accessibility

**Comment by Gravatronics** [comment]
Double clicking on inline editors (examples: "Edit" links in thread list, "Edit Thread" button on thread page, "Edit" button on event page) does not work anymore – probably because the first dropdown option is focused.

Double clicking on the "Edit" button of posts, however, still works. A single click on that button does not focus the first dropdown option.
