### ISSUE TITLE
Add option to make deprecated functionality inaccessible

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#2789]
To ease migrating from deprecated functionality to the “new version” it should be possible to prevent using this deprecated functionality and make the old calls fail hard.

- [ ] Option `ENABLE_DEPRECATION_WARNINGS`
- [ ] Function `\wcf\functions\deprecatedFeature($since, $linkToDocs)` (*) which is a no-op if the option is disabled and `throw`s otherwise.
- [ ] Similar function for JavaScript
- [ ] Update deprecated methods to first call this function
- [ ] Update deprecated class files to call this function before defining the class (i.e. when the file is being autoloaded)

(*) `$linkToDocs` points to an article (or an anchor within one) on `docs.woltlab.com` that explains what changes have to be made in order to migrate to the new code.

**Comment by mutec** [comment]
I hope this can be used with third party links too?

**Comment by dtdesign** [comment]
Sure, the remark above is meant for our products. It's a long-running issue that API changes (or in this case, new APIs) aren't documented that well and especially moving from one API to another involves far too much digging through code.

Pointing to an url makes it much easier to provide meaningful code examples rather than simple one-liners that can easily get out of date and leave a lot of questions.

**Comment by TimWolla** [comment]
I created a WIP PR #2798 with a slightly different API design: The extra information is automatically pulled out of the `@deprecated` annotation to prevent redundant or differing information. The link to the docs should be added to the annotation.

Please comment there with your opinion.
