### ISSUE TITLE
Prevent MySQL's engine substitution

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#2827]
The `sql_mode` set during the connection process does not include `NO_ENGINE_SUBSTITUTION`, which would prevent MySQL from picking a different storage engine if the requested one is unavailable.

We already check for InnoDB support, but some strange hosts have disabled MyISAM, causing the search indices to be created using InnoDB. This is actually a problem, because it uses a slightly different syntax that cause the query to fail.

**Comment by TimWolla** [comment]
I was just checking the `sql_mode` manual for MySQL and noticed `TRADITIONAL` which sets `NO_ENGINE_SUBSTITUTION` and prevents other MySQL stupidity as well (e.g. hard failures for division by zero).

Maybe we should use the former instead of the latter?

**Comment by dtdesign** [comment]
From https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sql-mode-combo:
`TRADITIONAL` is equivalent to `STRICT_TRANS_TABLES`, `STRICT_ALL_TABLES`, `NO_ZERO_IN_DATE`, `NO_ZERO_DATE`, `ERROR_FOR_DIVISION_BY_ZERO`, and `NO_ENGINE_SUBSTITUTION`.

Warning are already converted into errors on the PHP side through `\PDO::ATR_ERRMODE` and our general handling of PHP warnings as fatal errors.

However, `NO_ZERO_DATE` could be an issue, because it is sometimes used to represents `null` values, especially in third party extensions. As long as the code is aware of this, I don't see a reason to deny this behavior and thus `TRADITIONAL` might go too far.

In related news, I've noticed that `ANSI` is defined to include `ONLY_FULL_GROUP_BY`, making our default `sql_mode` a bit redundant?

That said, how about we use this sql_mode instead:
```
ANSI,STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION
```
`NO_ZERO_IN_DATE` simply denies values such as `2019-00-28`, but does permit `0000-00-00`. I don't think we need `ERROR_FOR_DIVISION_BY_ZERO`, dividing by zero will _effectively_ raise an exception anyway and changing this to an error might have an impact on userland code that expects a warning. This might be rather unlikely, but at the end of the daywe gain nothing from using an error here.

**Comment by TimWolla** [comment]
> Warning are already converted into errors on the PHP side through `\PDO::ATR_ERRMODE` and our general handling of PHP warnings as fatal errors.

Warnings are completely ignored by PDO (I actually checked that before writing my reply) :roll_eyes:. You can check this by executing:

```
mysql> SELECT CAST('0000-00-00' AS DATE);
+----------------------------+
| CAST('0000-00-00' AS DATE) |
+----------------------------+
| NULL                       |
+----------------------------+
1 row in set, 1 warning (0.02 sec)

```
which causes a warning in MySQL CLI, but simply works in PDO. The only thing `$driverOptions[\PDO::ATTR_ERRMODE] = \PDO::ERRMODE_EXCEPTION;` does is converting MySQL *errors* into Exceptions instead of converting *errors* into warnings (which then get turned to Exceptions by our error handler).

Unfortunately there appears is no (easy) way to pull MySQL warnings from PDO. MySQLi exposes [`warning_count`](http://php.net/manual/en/mysqli.warning-count.php), PDO does not. Attempting to get the number of warnings by hand (`SHOW WARNINGS` / `SHOW COUNT(*) WARNINGS` / `SELECT @@warning_count`) always fails with: 

> SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

Even when I enable emulated prepared statements, buffered querys and force the old query to be garbage collected. Replacing the query with a simple `SELECT 1` works. No idea whether I am doing this wrong.

> However, `NO_ZERO_DATE` could be an issue, because it is sometimes used to represents `null` values, especially in third party extensions. As long as the code is aware of this, I don't see a reason to deny this behavior and thus `TRADITIONAL` might go too far.

Developers don't tend to use actual `DATE` columns. It's either an unix timestamp or a `(VAR)?CHAR`.

> In related news, I've noticed that `ANSI` is defined to include `ONLY_FULL_GROUP_BY`, making our default `sql_mode` a bit redundant?

Not in MySQL 5.5, which is our current minimally supported version, so that one still is required.
