### ISSUE TITLE
User still gets e-mail notifications from a section (new threads/new posts) he lost access to

### ISSUE THREAD

**Issue by artgru** [WoltLab/WCF#2885]
Currently there is no way to prevent from sending an e-mail notification to the user who lost access to a specific forum, which means he still gets the e-mail notification (if enabled in profile notification settings) about new threads and new posts in watched threads (incl. content).
That leads to a potential security risk, cause a user without rights to the specific forum still sees the activity in it.

Tested out in WoltLab Suite™ 3.1.7 pl 1

**Comment by dtdesign** [comment]
We've looked into the underlying issue and there is no simple way to resolve this:
1. Subscriptions are not validated when triggering the notification. This makes absolutely sense and avoids a complete performance nightmare.
2. Permissions can be lost through a lot of different ways and because of the potential number of affected users, there is no sane way to validate subscriptions at any of these stages.
3. The permission checks at runtime are heavily focused on the active user, in fact there is no sane way to  efficiently verify the permissions of another user.

We plan to integrate a new worker type that can be used to validate the subscriptions of one or more users, enabling administrators to run this expensive process at their own discrection. Unfortunately, this would require quite a lot of changes to the inner workings of the permission system and its integration the apps, therefore we can address this at earliest with WSC 5.2.

There is one bit that was overseen: The outcome of this issue is a bit more limited, because only the first notification of a type will trigger a notification. This means that successive new posts or threads will not trigger a notification, unless the notification was marked as read. However, once the user attempts to review this notification, the permissions are validated and in case of a mismatch the notification is discarded and the subscription is terminated. At the very worst, the user is able to obtain exactly one email notification, but no further emails are generated for this purpose. This is far from being ideal, but at least limits the impact of this issue.

**Comment by jens1o** [comment]
@dtdesign Could you please elaborate on why this is not classified as a security issue? Users could potentially get access to confidential information they lost access to for a reason (-> unintended disclosure of information).
