### ISSUE TITLE
Provide IP-Address modal within WSC itself

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#2893]
The template should be location in the WSC's folder in order so prevent code duplication and make it easier for 3rd-party-developers to use this feature in a highly consistent way.

**Comment by dtdesign** [comment]
It would make much more sense to store the ip addresses in a centralized storage, which would make it much easier to identify content created by the same ip address. The current implementation is focused around the individual feature, for example, the dialog for forum posts is highly specialized towards posts and does not include any data from other sources.

Moving the template from the forum app into the core doesn't really solve any issues, especially because it's not generalized enough to really benefit other use cases.
