### ISSUE TITLE
Collation of wcf1_smiley makes it impossible to use emoticons from SMP

### ISSUE THREAD

**Issue by Valaphee** [WoltLab/WCF#2907]
I developed a plugin called "YoungGay Emoji" and this plugin can't be added because in order to work properly I need to change the collation of "smileyCode" in the table wcf1_smiley.

Because in the implementation of MySQL's utf8mb4_unicode_ci is a (I think) failure because smileys are "case sensitive" where the information gets lost in case insensitive and only 4 smiley codes in the Supplementary Multilingual Plane are unique.
https://www.unicode.org/charts/PDF/U1F600.pdf

And I wish that the smileyCode can be updated to be utf8mb4_general_ci or better utf8mb4_bin because there is real way to ease the use of smileys, because a lot of mobile users, will use the SMP and not something like "`:)`" or "`:rofl:`"

Kind regards,
Kevin L.

**Comment by dtdesign** [comment]
This will not be supported, because your use case would require us to drop case-insensitive matching of smiley codes, therefore `:foo:` and `:Foo:` would no longer be treated as equal. Recognizing smilies regardless of their casing is an actual feature, not a side effect of the implementation!

The smiley system isn't designed for this purpose, instead you should look forward to alter the font family definition. Prepending an emoji font would make much more sense, you would gain a consistent use of emojis without interfering with the actual font of choice:
```css
font-family: 'Noto Color Emoji', sans-serif;
```
