### ISSUE TITLE
uninstallation-script "PIP" useless without possibility to load classes

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#2918]
It's not possible to use the own app's classes (especially the DatabaseObjectList/Action-classes) in order to safely remove all files from the server. Which means that this feature is useless to apps.
`APP_DIR`, `WCF::getActiveApplication()`, `WCF::getPath('app')` aren't working - so (for me) there is no way to even get the application's path.

**Comment by mutec** [comment]
Not sure what the actual sense of that thing is. I can't event access my additional database columns.
@dtdesign could you please give me a statement how to use that "feature" in any way - no matter what I actually want to to I just can't?

**Comment by dtdesign** [comment]
Would you be so kindly to explain what problem you're trying to solve with it? The uninstallation pip works just fine for the purposes it was built for, but as with all tools, not everything is a nail.

**Comment by mutec** [comment]
I need to write some information to another column (created by my package). In case the administrator wants to uninstall the package, the original data should be restored (=> copy my column's content to the original column). Buut it says always that my column doesn't exist (anymore) - no matter which position or run-type the sql-instruction got.
For me I just can access the classes within the WSC directory and delete files by iterating over a directory or calling them directly and manipulate others package's tables/columns but not those I'd need to access.

**Comment by dtdesign** [comment]
The uninstallation script is designed to restore the system to a previous state where the package was not installed. One example for this approach is the default sort order for the members list, that is reverted to a "sane" value once the forum's "wbbPosts" column is no longer available.

The "file" PIP is guaranteed to be the last PIP that is executed during the removal and the uninstallation script is invoked immediately before the files are purged - this is required to preserve the uninstall script from being deleted before it got executed. However, anything else has been removed already, including but not limited to database tables and columns. **You cannot access any of this data at this point, because it's simply not there anymore.**

Additionally, apps that are being uninstalled are marked as tainted at the start of the process, suppressign them from being initialized at all. This explains, why the namespace is no longer known to the system. The uninstallation script is very limited, because it was **purpose-built to revert changes to foreign data** that would be not achievable in any other way.
