### ISSUE TITLE
System Requirement Check during installation or searching for updates

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#2943]
Since it was partly implemented in the past, I'd love to see a possibility to provide the system requirements via package-information or/and the updateservers.

I'd thought about those requirements at least:
- PHP-Version Minimum
- PHP-Version Maximum (warn instead of blocking an installation)
- PHP-Extensions needed (as a diff to the extensions required by WSC itself; maybe including a Version Minumum)
- Free Disc-Space Minimum (if customer's server can fetch this information; unpacked archive's size)
- Availability of the site via HTTPS

**Comment by dtdesign** [comment]
The current package system is not flexible enough to handle this in a graceful manner, especially the workflows of the package system are too dated. Requirements can change during the lifetime of a package, this can even cause mutual exclusions due to requirements defined by other packages. Examples for this would be a requirement of PHP 8.0, but having packages that only support up to PHP 7.4 which would break with PHP 8.0.

We're currently working on a concept (read: idea, not any actual code) for a new package system that could gracefully introduce these changes, along with a lot of other long outstanding improvements, maybe even the support to truly disable _any_ package.

That said, I will close this for housekeeping reasons, because it will overlap with the new concept. There is no strict ETA though, it may take some while before we can bring it up for discussion.
