### ISSUE TITLE
Show Modal including License-Name and/or text before installations and updates

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#2944]
Providing the license's name and link or text (via Proxy or/and for white-listed sites) would be more developer-friendly.

**Comment by dtdesign** [comment]
There will be no modal for the license implemented, because it doesn't solve anything. Let me explain:

License terms are quite a difficult terrain, because there is a lot of laws that deal with it, especially local laws. There are a lot of bases to cover and if you fail to comply with some parts, the whole confirmation parts turns void.

For example, license terms for paid plugins/apps/styles/whatever need to be presented to the buyer at the time of purchase. The buyer must be able to read the whole terms beforehand and must expressly accept them during the purchase. This then becomes a legally binding part of the contract and the buyer must obey the license terms (as far as legally possible/applicable).

Displaying the buyer the license text during the installation (or update) or prompting to accept them is completely useless, because it is not legally binding. You can't even prove that they accepted the terms, and again, even if they did at that point, it would be void.

I always giggle when I receive an email that contains a text passage like "bla bla, if you are not the intended receipient of this message, bla bla". These are super funny, because this is a one sided agreement and thus completely void, you cannot force this upon somebody, without them agreeing to it in the first place.

We can understand where this idea comes from, but frankly, this is not how the laws work and such a feature would only do one thing: Annoy users without providing anything legally valuable whatsoever.

PS: We're now shipping the proper license name and, if provided, license url with the Plugin-Store update servers. It's something ;)
