### ISSUE TITLE
PaidSubscriptionUserAction - groupIDs

### ISSUE THREAD

**Issue by UdoZa** [WoltLab/WCF#3068]
The functions add- and removeGroupMemberships call UserAction with parameter groupIDs being an array of strings. It should, however, be an array of integers - as in the rest of WSC.

**Comment by dtdesign** [comment]
Types are not guranteed at this point, because those are subject to type coercion at runtime. In fact, you must not rely on an integer being an actual integer, for instance, pdo_mysql may be linked to the crappy libmysql implementation, where everything is a string.

We do plan to migrate to strict types in the future along with forcing the superiod mysqlnd for pdo_mysql. For now there will be no change, simply because it doesn't solve anything.
