### ISSUE TITLE
Option to "unfix" the formSubmit in FormBuilder dialogs

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#3080]
![image](https://user-images.githubusercontent.com/1749344/65819902-6a32f280-e222-11e9-9a7d-79e870434574.png)

It would be perfect to be able to disable that fixed formSubmit optionally.

**Comment by dtdesign** [comment]
We put great emphasis on consistency, this includes the predictability of UI components, which means that the same type of component will always behave in the same way. Dialogs containing forms are designed to always show the form submit at the bottom, putting it anywhere else breaks the user expectations, forcing them to search the control element they are looking for.

Also, dialogs should be kept simple due to their constrainted dimensions, that greatly limit the available space.
