### ISSUE TITLE
Don't force custom updateserver-headers on status code 304

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#3096]
https://tools.ietf.org/html/rfc2616#section-10.3.5
Apach does not support custom headers if the status code is set to 304. The WSC should bypass the API-conformity for 304-returns.
https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/package/PackageUpdateDispatcher.class.php#L203-L221
We should check the status code before validating the api.

**Comment by dtdesign** [comment]
I'm not a big fan of the current state of the update server API, it hasn't aged very well, especially given the numerous additions over the years.

There are some ongoing plans for a new communication protocol that changes the way those package lists are computed, eventually reducing it into a single endpoint. I do intend to ship this new API with 5.2, but there are still some unresolved issues as well as some peformance considerations, so please take this with a grain of salt.

However, I have no intentions to make any changes to the existing API behavior, it does work just fine with nginx and possible some other webservers too. The RFC does not apply here, because the client (WCF/WSC) understands and expects this particular behavior, this isn't a general purpose API.
