### ISSUE TITLE
Allow entry point for Sentry

### ISSUE THREAD

**Issue by MatzeKitt** [WoltLab/WCF#3170]
Since the current error logging mechanism of the WoltLab Suite Core is quiet nice, especially with the new email notifications, it lacks some functionality:

- Real time notifications
- Notifications via other channels, e. g. Slack
- There is often no information which user triggered the error, which can be helpful for resolving the problem
- If the system is really broken, the notification may not being sent or not even logged

To overcome this, it would be really nice to have the possibility to integrate a error logging system like Sentry as soon as possible inside the code. This would resolve the above list of issues and maybe some more I didn’t notice so far.

Why Sentry? It is the de facto standard software for error logging, its free to use – either self-hosted or even the basic version via cloud hosting – and Open Source.

**Comment by RouL** [comment]
We're using self-hosted sentry at our company and I'm also using it for some private projects. I couldn't agree more that the WoltLab Suite could use this.
Probably also a nice addition for WoltLabs own Cloud service to watch the health of customer instances. ;)

**Comment by MatzeKitt** [comment]
So it actually won’t happen or did I miss something?

**Comment by dtdesign** [comment]
It has been on our list for way too long already and there are some fundamental design decision that are blocking a reliable integration of such a service. We do believe that the integration of services like Sentry can be beneficial to some extent, but for various reason this is not a priority for us for the next 1-2 years.

We’ll revisit the integration of such services at a later point in time.

**Comment by syntafin** [comment]
As the time goes on, after 3 years I am not sure if Sentry as wished here would be a good solution.

For me, I dropped Sentry in Personal projects because of performance problems when the capturing was active.

**Comment by dtdesign** [comment]
“Sentry” is just one answer to a much broader question. We never really focused on that particular product but rather seen it as an example for a class of products that attempt to solve this kind of problems.

**Comment by Fighter456** [comment]
> We’ll revisit the integration of such services at a later point in time.

Apart from the fact that I am no longer interested in it due to the fact that I have turned away from your products, I would like to ask anyway:

If such an integration (whether for Sentry or something else) isn't completely off the table, then why is the issue closed as "completed" (which is totally wrong) instead of leaving it in an open state in the backlog?

**Comment by dtdesign** [comment]
> If such an integration (whether for Sentry or something else) isn't completely off the table, then why is the issue closed as "completed" (which is totally wrong) instead of leaving it in an open state in the backlog?

I’m not sure why it reads “completed” and at the same time this appears to be the result when the issue is simply being closed. I don’t think its possible to change the message.

Regarding the backlog: We’re removing items from the backlog that have been postponed over and over again and it’s clear that we either are unable to take action in the near feature or do not intend to make changes. In this particular case such an integration requires us to make significant architectural changes that isn’t worth the trade-off neither at this point nor in the foreseeable future.
