### ISSUE TITLE
Remove BackgroundJobs triggered by a blocked user on ban action

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#3208]
It may be confusing for some administrators that banning a user won't stop the WSC from sending notifications, conversations, mails or whatever.
So it might be good to cancel every job that has been triggered by that user.

It would be good too, if there was a warning in case there are more than x jobs enqueued since that might be a helpful hint for preventing (or stopping) spam.

**Comment by dtdesign** [comment]
We're looking forward to implement a different kind of mechanic that will validate email notifications before sending them out. This is a much more focused approach and does not have unwanted side effects caused by the suggested dismissal of arbitrary background jobs regardless of their purpose. In addition, we can implement the aforementioned logic without requiring third party developers to modify their code.
