### ISSUE TITLE
Possible multilingualism problem

### ISSUE THREAD

**Issue by MenesesEvandro** [WoltLab/WCF#3214]
I am testing multilingualism features and found a possible problem.

I don't know if it should work like this, but if the multilingual system is active and the user chooses to view the content in only 1 language (image 1), he can still change the language of any given article (image 2).

And if they select the language that is not the preferred language and leave the article, the user will see the teaser in one language and when clicking to read, will read in another, because, at some point, he read and changed the language of the article.

<img width="810" alt="Captura de Tela 2020-04-16 às 19 01 30" src="https://user-images.githubusercontent.com/9220419/79513080-5bbef380-8019-11ea-8119-5dea8c7d0691.png">

<img width="220" alt="Captura de Tela 2020-04-16 às 19 01 59" src="https://user-images.githubusercontent.com/9220419/79513097-65e0f200-8019-11ea-9884-65c1931da24a.png">

**Comment by Dukemasters** [comment]
Hi Evandro,
I translated the Suite also in Portuguese and can say the whole multilingual system works fine and like it should be. Okay, there are always things to make better or in another way, but in the main important things it's okay. I think I know what you mean here. Therefor I will give you a tipp, to test it, you should always activate all installed content languages. Otherwise you have problems in overlooking the whole system. Feel free to test it with Portuguese, perhaps also Spanish, in my forum where it's also possible for normal users to create CMS articles. Lots of greets

**Comment by MenesesEvandro** [comment]
Yes...

It works great!

But I think if the user choose Spanish language only, they don't have to access the English content.

And if they change to English, next time they access, the content will be displayed in English, due cookie settings.

**Comment by Dukemasters** [comment]
I'm not sure if I've understooden correctly. When we speak about articles of CMS, they are multilingual, which means that the articles are created in ALL languages activated/installed in ACP. 
Or in other words, if you create an article, you have to write the article in all installed languages, no matter which one you have activated in user control panel. But there (UCP) you choose in which langs you will see the content. If you have only 2 langs, like you, you have to create your article in both langs, better the content have to be created in both langs. If you speak about forum articles, there it is possible to change the language, because you can create the articles only in one language, no matter how much langs are installed. If you change the language like you said, yes, then you will see it only in English, if you have choosen English at least.

**Comment by MenesesEvandro** [comment]
Take a look at this video:

https://1drv.ms/u/s!AmSRtS4dDvMsiM0Sl1XgX63jaPHb4w?e=XMMyXk

I'm just selected Português (BR) (Brazilian Portuguese) as content language.

But I can change the content to any given language. I shouldn't, right?

If I choose only one language, that's unnecessary to show all languages available and it may cause some trouble with some users also...

**Comment by Dukemasters** [comment]
Yes, I just tested it today. Now I know what you mean. 
The interface language is the most important one, it's your system language. 
But if you want to create an article only in one language you can do it. Whenever you click "Create article" then you are asked if you want an monolingual or a multilingual article. If you create a monolingual arcticle there are no flags to choose. In my forum there are ONLY multilingual articles. But write one if you want and check it.
![Screenshot_2020-04-22 Artículos - Panel de control de administración - COSIREX 💥 Comunidad para personas interesantes](https://user-images.githubusercontent.com/28341981/80028129-f79ea280-84e4-11ea-87de-cd3cae76d554.png)

**Comment by MenesesEvandro** [comment]
That's not quite it.

I don't want to write any articles. I'm just logging in as a standard user.

If my interface is in English and the selected content is Spanish, I understand that when entering the list of articles I must see the articles in Spanish, since my content is in Spanish.

It turns out that the system shows the content in the same language as the interface. It does not matter the language of the selected content.

I made a new video ... The content displayed on the page should respect the user's content language options, but it overlaps the language of the content by the language of the interface...

https://1drv.ms/v/s!AmSRtS4dDvMsiM0ht552k3u8mW8cmg?e=3r8pjk

**Comment by Dukemasters** [comment]
No. 
Interface language is to watch the articles in the interface language.
Content language is ONLY for writing articles or forum threads. If you have english as interface and spanish as content lang, and you write a new article in monolingual language then it is always the content language you have chosen.

**Comment by MenesesEvandro** [comment]
> No.
> Interface language is to watch the articles in the interface language.
> Content language is ONLY for writing articles or forum threads. If you have english as interface and spanish as content lang, and you write a new article in monolingual language then it is always the content language you have chosen.

It seams to be a slight problem with that...

"Limits visibility to content associated with the selected languages."

It doesn't!

I can see all content associated with any languages.

And if the interface and content language isn't the same, the main content I see is in the interface language. Should be in content language, right?

I think it works great at forums, but with articles just seems that the system doesn't work as it supposed to. The system is supposed to show the content in the selected content language, just like the forum.

**Comment by Dukemasters** [comment]
Yes, you are right. In forum it works better, or like it should. In CMS you see always everything, no matter which interface lang or no matter which content lang you have selected.
I know what you mean, and it's correct what you have written.

**Comment by dtdesign** [comment]
Articles and pages work a bit different and do not enforce strict visibility guidelines. On top of that the setting is designed for user generated content and articles/pages usually come from the site administrator.

We believe that there could be a good reason to access the content in a different language, especially because this is a choice that the user can make, not something forced upon them. The system will always try to present you the content matching your interface language, but a user can still access a different translation at their own discretion.

**Comment by MenesesEvandro** [comment]
@dtdesign I agree with you. Users always have the power to choose.

But the main content (the first to show up to the user) should be the same as the selected content language.

If the Interface language is different than the content language, the user sees first content related to interface lang. 

Interface: English
Content: German

The articles that show up first are not in the German language, they are in English. But my content is preferable to be in German in this scenario.

If I want to read in German I must open an English article and change to German.

In some way, the system is not looking at my preferences.
