### ISSUE TITLE
Add method to check for sufficient memory to process images

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3229]
We have many places with code like this

```
FileUtil::checkMemoryLimit($width * $height * ($extension == 'png' ? 4 : 3) * 2.1)
```

which could be moved to a central method (or to the image adapter?).

see https://community.woltlab.com/thread/272061-einf%C3%BChren-von-attachment-canmodifyimage/

**Comment by TimWolla** [comment]
I would like to add this method to the image adapters, because Imagick might have different requirements compared to GD. Unfortunately that would require modifying the `IImageAdapter` interface and there is no abstract class / trait that would allow specifying a default implementation.

Suggestions about this?

**Comment by dtdesign** [comment]
We could introduce a new interface that derives from `IImageAdapter` and that is implemented by all three classes (`ImageAdapter` + `*ImageAdapter`). Then, add a method `ImageAdapter::checkMemoryLimit(…)` that checks for the interface and passes it on to the implementing adapter. If the adapter does not implement it, run a pessimistic check in that class instead.
