### ISSUE TITLE
Add trophies tab on user profile page

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3255]
… instead of opening a dialog when clicking on the number of trophies (on the user profile page).

see https://community.woltlab.com/thread/278295-troph%C3%A4en-tab-im-benutzerprofil/

**Comment by dtdesign** [comment]
There are already more than enough tabs, besides that it would add very little value. We could consider reworking the overlay, for example, to use a double columned layout to provide a better overview.

However, the tab is merely trying to solve a symptom rather than addressing the actual issue of having too many "incremental" trophies. It would make much more sense to work towards adding some kind of leveling system for trophies that would effectively reduce the number of visible trophies: There is no value in displaying the "10 posts" trophy when the user already holds the "100 posts" trophy.
