### ISSUE TITLE
Support content position of tag boxes

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#3281]
see https://community.woltlab.com/thread/276098-schlagwortwolken-im-inhaltsbereich-erm%C3%B6glichen/

**Comment by BurntimeX** [comment]
To support the content positions we would need two additional templates (the forum has a custom template for the board tag cloud), because the current templates are not designed to be displayed in the content positions.

Furthermore, the number of tags shown (50) is probably too low to be displayed in the content positions. The number of tags should therefore be configurable per box.

IMO, implementation is not worth it because of the poor cost-benefit ratio.
