### ISSUE TITLE
Store sitemaps in own database table

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3376]
Currently, sitemaps are stored in "wcf1_object_type". Changes to the Sitemaps by the user are stored there as "additionalData". This value is potentially overwritten during a package update.

ref https://community.woltlab.com/thread/283340-sitemapreaktivierung-nach-upgrade-auf-5-2/

**Comment by joshuaruesweg** [comment]
I believe that storing the complete sitemap objects in the database is unnecessary. I like the current implementation very much, and would like to avoid that developers have to provide any SQL commands (or even a separate PIP file for sitemaps [avoid BC]). I have now spent a few minutes thinking about what happens when you save changed values in the registry (so also somehow in the database, so that they are protected from changes by the obectType PIP, but don't need a separate table)? I think that's the best solution, don't you?

**Comment by dtdesign** [comment]
The registry is a sufficient solution for now, it provides full backwards compatibility without causing too much a of change.

Picking the object types for sitemaps wasn't the best choice in the first place due to the constraints/side effects of the object type processing. However, this would be out of scope and introducing a new database table will only partially solve this. We'll revisit this somewhere in the future, possible along with an overhauled package system.
