### ISSUE TITLE
list-unsubscribe header

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3379]
Notification emails could also include the unsubscribe URL in the list-unsubscribe header.

**Comment by TimWolla** [comment]
For completeness a `list-id` header probably should also be generated. Having a look at the RFC I'd say that:

```
List-Id: New Post <com.woltlab.wbb.post.list-id.$wsc_domain>
```

would be an appropriate format, giving a distinct List-Id per notification type.

**Comment by TimWolla** [comment]
Having read [RFC 8058](https://tools.ietf.org/html/rfc8058) the implementation of this is mostly relative straight forward: Two additional headers (List-Unsubscribe / List-Unsubscribe-Post) need to be added. The former contains a single link that already is part of the mail body. The latter contains a static string. List-Id is not part of that RFC, but should be added for completeness. The necessary information (which objectType does this notification belong to)  is readily available as well.

The biggest hurdle is that while touching this part of the code the NotificationDisableAction should be changed to a NotificationDisableForm, because immediately performing actions based on GET requests will cause issues with antivirus software that fetches all links within an email to check them. This most likely will require deleting the old NotificationDisableAction with an update script, similar to the MailForm: https://github.com/WoltLab/WCF/blob/b6ea711aed85bba8a1169e98a2693c172d2354ab/com.woltlab.wcf/package.xml#L54

The behavior of that form should then be as follows:

- If a GET request is performed (user manually clicks the link): Show an explanatory message and a single button that actually performs the unsubscribing. This behavior is established within the industry for unsubscribing all kinds of newsletters and thus cannot be considered an unnecessary hurdle.
- If a POST request is performed with `$_POST['List-Unsubscribe'] == 'One-Click'`: Perform the unsubscribing and send nothing but an empty page with a 200 / 204. Specifically a redirect to a “success page” *must not* be used:
    >   The mail sender MUST NOT return an HTTPS redirect, since redirected
    >   POST actions have historically not worked reliably, and many browsers
    >   have turned redirected HTTP POSTs into GETs.

RFC 8058 also requires the additional headers to be DKIM signed. The responsibility for that lies with the administrator of the mail server. Not performing this signing will fail gracefully, though: The one click button simply will not be shown within the recipient's mail client.

**Comment by TimWolla** [comment]
> This most likely will require deleting the old NotificationDisableAction with an update script, similar to the MailForm:

Instead the new form could be called NotificationUnsubscribeForm and the old action performs a redirect.
