### ISSUE TITLE
Redesign of the moderation panel

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3381]
The entire moderation panel is quite old and the original layout was modified at multiple occasions, but the the UX did not keep up. We need to review the panel, analyze the workflows and work out a new layout that is designed around the ever changing requirements.

* [ ] Add a „Assign yourself“ button, like Github (@joshuaruesweg)

**Comment by Sir-Will** [comment]
I did put in a lot of thoughts into this before, as the current moderation system requires a lot of navigating and clicks.
In a lot of cases, seeing only the reported content is not enough to make a decision. Especially for posts, the context is very important. Therefore, you have to go through a lot of pages to get the all the information.

I think instead of having a dedicated site for the moderation entry, it would be a lot better to have a moderation view of the actual site with the content.

For example, for a reported thread post:
When clicking on a moderation entry in the moderation list, it opens the normal thread page with some moderation tools. The reported post is highlighted to make the targeted content clear, and at the bottom of the screen you have a collapsible floating moderation tool.
In the moderation tool you have some information about the author (like registration date, amount of posts...) and a select option to choose what to do (delete post, delete post and ban user, ban user and delete all users content, close report...).
Moderation comments could be inside the moderation tool as well, by scrolling below the author information.

**Comment by dtdesign** [comment]
Thank you @Sir-Will for your valuable input. Your suggestion does tick a lot of boxes and makes for a much better experience, inline actions can provide much more feedback without introducing redundancy.
