### ISSUE TITLE
Why is version >= 6.5 < 7.0 of guzzlehttp used?

### ISSUE THREAD

**Issue by TitusKirch** [WoltLab/WCF#3567]
Why is version >= 6.5 < 7.0 of guzzlehttp used? What speaks against using version >= 7.0?

https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/system/api/composer.json#L18
https://github.com/guzzle/guzzle/releases/tag/7.0.1

**Comment by joshuaruesweg** [comment]
Guzzle 7.0 needs PHP in version of 7.2 or higher. We only We require PHP version 7.0 or higher. Therefore we are currently not able to use Guzzle in version 7.0.

**Comment by TitusKirch** [comment]
PHP 7.0 is since 10 Jan 2019 and php 7.1 since 1 Dec 2019 end of life. PHP 7.2 will be end of life in a few weeks, why do you still take this as a minimum version?

**Comment by dtdesign** [comment]
Ubuntu 16.04 LTS is still supported until April 2021 and ships with an actively maintained PHP 7.0. The same applies to Debian 9 LTS (Stretch) which also ships with PHP 7.0 and is supported until 2022.

We'll be increasing the PHP requirements to 7.2 with WoltLab Suite 5.4. PHP 7.3 adds no real benefits over 7.2 and 7.4 will most likely not have sufficient support among our customers. It's still some time until WoltLab Suite 5.4, so that's not entirely fixed in stone, although still likely. On the other hand, we do observe that more and more hosting companies start offering newer PHP versions way sooner than they did before. Only time will tell.

Heck, I would love to bump the requirements up to PHP 8 once it gets out, there are so many useful new features and improvements. But in reality, it is simply not feasible if you're offering the software for a wider audience with so many bad hosting companies out there.

It ain't fun to artificially limit yourself to old versions for the sake of compatibility. There is a hidden cost of this restriction, caused by the lack of newer features that improve the producitvity of developers. It is really no fun being tied to ancient PHP versions.

**Comment by TitusKirch** [comment]
Thank you for this detailed explanation. I can understand all the reasons, but why do you go a different way here than "bigger" frameworks/CMS systems? They have the same "problem" but partly use current PHP versions.

**Comment by dtdesign** [comment]
The decision when to bump the requirements is very specific to your audience and their adoption rate of newer PHP versions. You can expect developers to act accordingly when requiring newer PHP versions, but Average Joe is at best only remotely aware that something like PHP exists. Looking at our direct competitors, two of them require PHP 7.1 and one requires PHP 5.6, both PHP versions are ancient by today standards. This is also the same reason, why WordPress recommends PHP 7.4, but is still compatible with PHP 5.6.

That said, "pure" frameworks increase the requirements way earlier, because their target audience are developers that are able to determine these things themselves and that are more likely to run newer versions anyway.

**Comment by TitusKirch** [comment]
And thanks again for your answer. Even if I find it a bit negligent to support eol versions, I can at least fully understand this now from your point of view.
