### ISSUE TITLE
Support customURL with page type system

### ISSUE THREAD

**Issue by Sir-Will** [WoltLab/WCF#3794]
Currently, it's not possible to use `customURL` properly with the page type `system`. Would be great if this can be supported.

While the following adds it to the ACP, it prevents the template from loading until the page is being manually updated in the ACP.
```xml
			<content>
				<customUrl>legal-notice</customUrl>
			</content>
			<content language="en">
				<title>Legal Notice</title>
			</content>
			<content language="de">
				<title>Impressum</title>
			</content>
```

**Comment by dtdesign** [comment]
The ability to define custom URLs is a privilege of the adminstrator to customize the urls and should not be used by developers. I'm not even sure why it is possible to define them like this, because this is clearly not intended to work that way.

**Comment by Sir-Will** [comment]
I agree with that but in some occasions it would be useful (like site specific plugins) and with the other page types already supporting it I don't see why `system` is not supported.

**Comment by dtdesign** [comment]
It is quite difficult, because system pages are not language dependent by default and the behavior of the URL might not be predictable depending on the environment. Their behavior is entirely subject to their implementation. Additionally, the other page types do not have a generic url and absolutely require actual custom urls to be even accessible. This is not true for system pages.

There is little to no value to provide overrides for system pages by default and I would even go that far to consider this a harmful practice.
