### ISSUE TITLE
Failed cronjobs cannot be reactivated

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#3841]
If a cronjob is set to `canbedisabled=0`, it cannot be reactivated by the user after an automatic deactivation due to a failure during the execution of the cronjob.

**Comment by joshuaruesweg** [comment]
The question here is whether to allow activation here or, in my opinion the much better way, to disable the automatic deactivation of these cronjobs so that the cronjobs are always active (even if they fail, for whatever reason). In fact very few administrators regularly check whether all cronjobs are activated and it is usually only noticed when errors occur due to the cronjob not being active.

**Comment by dtdesign** [comment]
The whole mechanism stems from a time where cronjobs could indefinitely block the execution of other queued cronjobs and no proper error reporting was implemented. It might make sense to modify the behavior when a cronjob has failed 3 times:

1. If it can be disabled:
  * Disable it.
  * Log an error to the log.
2. If it cannot be disabled:
  * Log an error to the log.
  * Reset the fail counter to 2 (!).
  * Compute the `afterNextExec` value and set that value to `nextExec`.

The important bit is the modification of the fail counter and the date of the next execution. Both are intended to force the next regular cycle to be skipped to prevent other cronjobs from being blocked. If the cronjob is broken, this change will cause it to be only executed once every 2 cycles, while dumping a metric ton of errors into the log.

**Comment by joshuaruesweg** [comment]
I have implemented and tested the whole thing once. Unfortunately, cronjobs can still be blocked. For example, if the cronjob runs every five minutes, the cronjobs that run every 10 minutes are blocked. How about we sort cronjobs beforehand according to how often they have failed. The cronjobs that have already failed are then executed last so that they cannot block any normally running cronjobs.

**Comment by dtdesign** [comment]
> How about we sort cronjobs beforehand according to how often they have failed. The cronjobs that have already failed are then executed last so that they cannot block any normally running cronjobs.

That's a great idea!
