### ISSUE TITLE
Hide the SMTP password in the options

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#3975]
* [ ] Hide the SMTP password from the view similar to the password for package servers.
* [ ] Discard the password when the username is set to an empty value.

See https://community.woltlab.com/thread/286762-smtp-kennwort-ausblenden/

**Comment by TimWolla** [comment]
I don't really see how this could be achieved without hacking around deeply in `OptionHandler` which I'd rather avoid. For the package servers this was easy, because it was a dedicated form with full control over the value / input handling.

I'd “Won't fix” this.

**Comment by dtdesign** [comment]
How about we simply use a dedicated option type that does not expose the password? It's a bit difficult to determine how we should handle attempts to remove the password in case of a generic type.

**Comment by TimWolla** [comment]
> How about we simply use a dedicated option type that does not expose the password?

The API still doesn't allow this to be implemented without largish changes to the `OptionHandler`. This dedicated option type would need to know about the existence of the corresponding username option as well as the username's value to determine the save value for the password:

https://github.com/WoltLab/WCF/blob/ff1f052337c960fb7ab3c952f65bce00f0876c7f/wcfsetup/install/files/lib/system/option/OptionHandler.class.php#L397

It's not that it's super hard to implement. But it requires one to be careful, so I'd rather avoid changes there **just** to support this, especially since the whole option system is in need of a bigger modernization (cf. https://github.com/WoltLab/WCF/issues/3503#issuecomment-683284035).

**Comment by dtdesign** [comment]
Sounds fair. This "issue" isn't worth the trouble, especially since the access to the options should be considered a highly sensitive area which should be in general not accessible to anyone unless absolutely necessary.
