### ISSUE TITLE
Add dedicated permission for GDPR export

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3993]
The GDPR export includes all kinds of internal and sensitive information. As of right now the export is protected by the `canEditUser` permission. However administrators that may edit users in general might not be authorized to edit or view all the information within the export.

This includes the email addresses which are only shown if the administrator is authorized to edit email addresses. This might also include IP addresses or other information from plugins (e.g. payment data).

**Comment by SoftCreatR** [comment]
A plugin already exists for more than 2 years: https://shop.softcreatr.com/product/64-dsgvo-admin-export-berechtigung/

However, 5.4 Alpha 1 is excluded (because I knew that it will be just a matter of time until you'll implement this by yourself). But if you plan to add this in WSC prior to 5.4, I would like to ask you not to call it `admin.user.canExportGdprData`, because this one is reserved by our plugin and may cause unnecessary collisions.

**Comment by TimWolla** [comment]
@SoftCreatR _Unfortunately_ the permission name you selected is the most fitting one. We're going to make the adjustment for WoltLab Suite 5.4 only. I'd appreciate if you could perform a review of #4013. Thanks!

**Comment by SoftCreatR** [comment]
> Unfortunately the permission name you selected is the most fitting one.

That's absolutely fine. I've just published an update of our extension, so nothing changes when upgrading to 5.4, when our extension was used in 5.3 or ealier.
