### ISSUE TITLE
Add `onRequire` helper function for RequireJS

### ISSUE THREAD

**Issue by Sir-Will** [WoltLab/WCF#4161]
There doesn't seem to be an easy way to modify the functions of modules. Having some kind of `onRequire` helper function for RequireJS would provide a useful way of modifying the modules. Example: https://gist.github.com/rpendleton/4b6281e88baef91ecca9

I'm currently looking into completely changing the `AjaxStatus` overlay. With the html being in the JavaScript function it's not possible to directly modify it.

**Comment by TimWolla** [comment]
You are probably interested in either https://requirejs.org/docs/api.html#config-map or https://requirejs.org/docs/api.html#config-paths.

I'd advise against doing any kind of monkey patching, though. The internal API of the modules is not covered by any stability guarantees and outsides patches might break your site.

**Comment by Sir-Will** [comment]
Thank you, `map` seems to be a good way to do it. Though I couldn't find a way to override the `_init` function with extend, is this not possible or am I missing something?

This is what I tried, it adds functions but doesn't override existing ones.
```js
define(['Core', 'AjaxStatus'], function(Core, AjaxStatus) {
	'use strict';

	return Core.extend({
		/**
		 * @see	AjaxStatus._init()
		 */
		_init: function() {
			...
		},
	}, AjaxStatus);
});
```

> I'd advise against doing any kind of monkey patching, though. The internal API of the modules is not covered by any stability guarantees and outsides patches might break your site.

I agree with heavy core functions but modifying the way the AjaxStatus is displayed shouldn't cause any issues.

**Comment by dtdesign** [comment]
> This is what I tried, it adds functions but doesn't override existing ones.

Because this is not how monkey patching works. You need to override the actual code before it is executed, which, depending on the execution order, is not even guaranteed for this particular method.

Also, since you can't access the module private variables, you will have to go much greater lengths to be able to modify it. You will have to pretty much re-implement the entire module. This is a dangerous road which will break compatibility eventually or introduce subtle bugs due to a mismatched behavior further down the line.

Please do not fiddle with internal APIs, they are internal for a reason, just because you can do things like monkey patching doesn't mean that you should. Monkey patching is not a feature, but a side effect of the crappy language that JavaScript is.

**Comment by Sir-Will** [comment]
Too bad, I really don't like the old-fashioned loading spinner in the middle of the screen.
