### ISSUE TITLE
Support options saving values as arrays

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#4186]
Since PHP supports arrays in constants for quite a few years, adding new option types that store their values in arrays has the advantage that the relevant code using these options does not have to split the values manually each time.

While #4128 was meant as a drop-in replacement for existing options, such new option types could only be used for new options as they break backwards compatibility.

**Comment by dtdesign** [comment]
This adds quite some complexity due to the need of a SerDes (e.g. JSON) to store the data structure in the database. I don't really see a benefit other than allowing newlines to appear within values, which is currently impossible with the multiline text type.

Arrays are a nice thing for sure, but I don't see how they actually solve a problem? If you require complex data structures in options, you are most likely not looking for an option to begin with. Even then, you can easily introduce a custom option type that maps to whatever data structure one needs.

Because of the backwards compatibility we cannot migrate our "own" options to the "new" type, eventually keep using the "old way" or causing a fragmentation among our options.

**Comment by dtdesign** [comment]
RFC: Are there any arguments that I am missing here? Is there a good reason for adding support for native `array` data structures in options?
