### ISSUE TITLE
Database-API: generate index named using all columns' names instead of the first one

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#4360]
https://github.com/WoltLab/WCF/blob/c29b75e0e43c5680f7d4182325b5958902997661/wcfsetup/install/files/lib/system/database/table/DatabaseTable.class.php#L237-L239

Currently the generated name relies on the first column name. So if I add an unique index on `['fooID']` and then add an index on `['fooID', 'barID']`, the following exception is thrown:

```
Duplicate index with name '255a4f50bf4ab719720b5cd466358242'.


File: /wcf/lib/system/database/table/DatabaseTable.class.php in line 242
```

**Comment by TimWolla** [comment]
I believe this is impossible to change after the fact, because then existing indices would no longer be detected. It's also not introduced with the PHP based DDL API, but already exists within the old SQLParser:

https://github.com/WoltLab/WCF/blob/a13f3b15eeff56a47bc8f04fd34c6f4420abd139/wcfsetup/install/files/lib/system/database/util/SQLParser.class.php#L411-L425

**Comment by Gravatronics** [comment]
As mentioned by @TimWolla, the implementation in `DatabaseTable` was chosen to match the implementation in `SQLParser` for cross-compatibility.
