### ISSUE TITLE
Force overwrite unknown database tables using a known prefix

### ISSUE THREAD

**Issue by dtdesign** [WoltLab/WCF#4410]
Most backup and restore features, such as Plesk's built-in capabilities, will only import the SQL dump, but not clean up anything else that was in the database. This causes database tables to remain even if those were not part of the original backup.

All database tables with a known prefix (such as `wcfN_`) should therefore be regarded as being part of the installation, even if they do not appear in the SQL log. Database tables without a known prefix will remain protected from changes if those are unknown to the SQL log.

**Comment by joshuaruesweg** [comment]
>All database tables with a known prefix (such as wcfN_) should therefore be regarded as being part of the installation, even if they do not appear in the SQL log. Database tables without a known prefix will remain protected from changes if those are unknown to the SQL log.

I have two solutions for this. 

1) During the installation, we request the prefixes of all installed applications and match them. 

2) We use a fixed list of prefixes so that we can match them. 

The first solution would have the disadvantage that the mechanism does not work if the installation of an application fails and you want to install it again. This is rather unpleasant for the user. Therefore, I am more inclined towards solution number 2. Or we trust that only tables are changed / created that the plugin needs and do not match with any prefix.

**Comment by dtdesign** [comment]
I do not see option 1 to be an issue.

The problem are insufficient restores of the database where only the tables contained in the backup are replaced. This causes "new" tables to be ignored, therefore those remain and will now exist despite the database being restored from a backup. In fact, some crappy control panel softwares do not re-create the database, which means that when the user clicks to restore dbX they do not get state X, but X' (X + new tables that did not exist at the time of the backup).

Yes, the approach 1 does not resolve the issue of failed app installations, but we got that covered pretty good. The only remaining issues are those aborted upgrades combined with crappy control panel softwares.
