### ISSUE TITLE
Memberlist one div toomuch.

### ISSUE THREAD

**Issue by noaim** [WoltLab/WCF#4488]
templates/compiled/2_wcf_1_team.php und 2_wcf_1_user.php

<div class="userIDDiv" data-user-id="<?=$this->v['user']->userID;?>"></div>

team.php: moved from line 2399 to line 2384 solved the issue.

user.php moved from line 323 to line 311

Memberlist shows entrys wrong, not in a row as it should. Like someone pressed a the magic enter button.

**Comment by mutec** [comment]
Those files are compiled and very individual. Without the exact code in them, this issue is useless.
Anyway it could be a plugin or some kind of style or template modification too, that's causing your issue.

**Comment by dtdesign** [comment]
@noaim I second what @mutec said, the compiled template is anything but a reliable starting point for your search. The compiled template actually includes other templates and depending on the use of custom themes, templates and plugins the actually executed template can greatly differ.

It would be best if you could provide a link to the affected site so that we can take a look into the page source to get some clues of where the issue stems from. If you're a customer and would like to not disclose your website, then please submit a ticket on woltlab.com.

**Comment by noaim** [comment]
https://www.noaim.eu/index.php?team/

using the original theme same issue.

**Comment by noaim** [comment]
the website is blocked with htaccess, i will open a ticket

**Comment by dtdesign** [comment]
The issue was caused by a faulty third party plugin that injected invalid HTML.
