### ISSUE TITLE
Replace Google Maps with OSM

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#4680]
WSC 6 (at the latest) should no longer use Google Maps. Instead, OSM (via Leaflet?) should be used, so people can use GDPR compliant maps on their websites. OSM allows using locally hosted Tile servers as well as remote ones (e.g. https://tile.openstreetmap.de).

Imho, there's no reason to continue the use of Google Maps, but I know, that this change is backward incompatible, so I suggest switching in WSC 6.

**Comment by BurntimeX** [comment]
Openstreetmap offers no functional advantages compared to Google Maps. At the same time, the website owner is still dependent on external providers, since hosting the map material will hardly be an option for most users.

We have therefore decided to continue to rely on Google Maps. In the future with a privacy friendly solution with user content based on WebComponents.

see https://github.com/WoltLab/WCF/pull/4972
