### ISSUE TITLE
Consider migrating to utf8mb4_unicode_520_ci

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#4919]
see: https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-sets.html#charset-unicode-sets-uca

`utf8mb4_0900_*` would be preferable, as this is more modern, but those are not supported by MariaDB.

**Comment by dtdesign** [comment]
Converting the charset is anything but fun and has proven to be causing all sorts of issues in shared hosting environments. Is there any particular reason of why we want to migrate to a different charset at this point?

**Comment by TimWolla** [comment]
To be clear: This is about the collation, not the charset. The utf8mb4_unicode_ci collation that is currently in use is based on the ancient 4.0.0 version of Unicode and has various issues with correctly sorting and disambiguating characters.

utf8mb4_unicode_520_ci would be a little newer (version 5.2.0) and is the latest version that is supported by both MySQL and MariaDB.

utf8mb4_0900_as_ci is MySQL only, based on version 9.0.0 and has the added benefit of the “as” bit in there, that means accent-sensitive, allowing you to have both Apfel und Äpfel in the same UNIQUE column.

MariaDB 10.10+ on the other hand supports uca1400_as_ci, based on version 14.0.0. That one is also accent-sensitive, but not supported by MySQL (and neither the 10.5 version that is the minimum for 6.0).

**Comment by dtdesign** [comment]
Doesn’t the change to the collation require altering all columns that currently contain string values?

**Comment by TimWolla** [comment]
Indeed it appears that this still requires a full table rewrite, at least in MariaDB 10.5.

**Comment by dtdesign** [comment]
Correct me if I’m wrong, but it looks to me as if there is no significant benefit to moving fron unicode 4.0 to 5.2, because important stuff like umlauts is still not handled properly in that version. It was quite painful to do the migration from `utf8` to 
`utf8mb4` and we should really think twice before going through this again, the burden on the ticket support was real.

The future doesn’t look that bright though, with MySQL seemingly stuck at unicode 9 and the company behind MariaDB being pretty much belly up at this point. It’s unlikely that they will converge any time soon and using different collations will make migrations between different hosts a true nightmare.

That said, you’re the expert here. If you think that we should migrate to `utf8mb4_unicode_520_ci` in 6.0 then we’ll do it, otherwise close this issue and don’t look back ;)

**Comment by TimWolla** [comment]
> and using different collations will make migrations between different hosts a true nightmare for shared hosting customers.

Absolutely agree here, that's why the proposal specifically was for the 5.2.0 that is consistent between both.

> If you think that we should migrate to utf8mb4_unicode_520_ci in 6.0 then we’ll do it, otherwise close this issue and don’t look back ;)

Probably not worth it then. That's why the issue is titled “Consider” instead of “Do”. We did the consideration now :smiley:
