### ISSUE TITLE
Allow *rand*() in enterprise mode

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#4967]
```
Template compilation failed: disabled function 'random_int' in template '__cms_box_24' on line 1
```

**Comment by SoftCreatR** [comment]
```
Template compilation failed: disabled function 'mt_rand' in template '__cms_box_24' on line 1
```

Are these functions disabled by purpose?

**Comment by dtdesign** [comment]
This sounds a lot like you are attempting to embed business logic in templates. What is the purpose of generating random numbers in a box that are stored nowhere?

**Comment by SoftCreatR** [comment]
Display a random image (1.jpg ... 10.jpg) for example.

**Comment by TimWolla** [comment]
While that still pretty much sounds like business logic that is best located within actual PHP code, we can see the value for the given use-case in combination with admin-created CMS boxes.

I've just added `random_int` to the allow-list. We won't add `mt_rand()` / `rand()` to keep the list of allowed functions focused without useless “duplicates”. Furthermore those two are a little questionable due to relying on seedable global state. See this PHP 8.2 RFC for some more details and a well-designed replacement API: https://wiki.php.net/rfc/rng_extension / https://wiki.php.net/rfc/random_extension_improvement
