### ISSUE TITLE
Icon Selector is missing brand icons

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5180]
Is there a reason why the icon selector does not contain brand icons? And/Or is there a way, to optionally include them in the selector?

**Comment by SoftCreatR** [comment]
Okay, maybe this was fixed in 1d9665a8d8f1221d52dfec3817211daf2dc6ecd9

I'll check that later.

**Comment by dtdesign** [comment]
Brand icons are not represented through an icon font and are instead embedded on-the-fly using an inline SVG. It’s incredibly expensive to load all those SVG ahead of time, which is why the decision was made to omit those icons from the icon selector. There is not a strong enough use case to justify the inclusion of brand icons in the selection.
