### ISSUE TITLE
Make `FontAwesomeIcon::$name` and `FontAwesomeIcon::$forceSolid` readable

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5209]
It would be good to be able to determine which icon is used.
Since the class is flagged as `final` for strange reasons there is no way to implement get-functions or other logic when needed.

**Comment by dtdesign** [comment]
I’m not sure why you would need to access the values at all? Everything you need to render the icon is already there?

**Comment by mutec** [comment]
I'm currently preparing several packages for WSC 6 - including the Shop.
There are several objects implementing `getIcon(): string` which should be replaced by `getFontAwesomeIcon()`, so one could use `forceSolid` if wanted/needed. For compatibility-reasons I'd like to keep `getIcon()` until the next major release, but I can't call `getFontAwesomeIcon()->getName()` in order to make the method return the same like before.

Another gimmick: If the class was not `final`, I could inherit that class and add a method wrapping `toHtml()` for displaying icons as disabled or doing other wrapping-stuff in extra methods:
![image](https://user-images.githubusercontent.com/1749344/211025203-23a0f1a7-2462-4934-9435-36b4e00dcffc.png)

**Comment by dtdesign** [comment]
Toggling `forceSolid` is unsafe, because you cannot make any assumptions about what they look like. For the free icons the change between solid and non-solid changes the meaning of the icon, also only some of the free icons have a non-solid variant. When using their paid font variants it becomes even more awkward, because you then start mixing bulky icons with thin(-ner) ones and vice versa.

> Another gimmick: If the class was not `final`, I could inherit that class and add a method wrapping `toHtml()` for displaying icons as disabled or doing other wrapping-stuff in extra methods:

This is a prime example of why this class is implemented as `final`. Everything it does is considered to be an implementation detail, for the same reason that `<fa-icon>` only exposes a minimal API surface, because whatever happens inside is not your business. The `{icon}` helper by intention does not offer any ability to apply CSS classes or any other form of formatting.

Everything you want to do must happen in the outer context of the icon. If you want to style it differently to indicate a state, such as disabled icons, then you will have to wrap the icon into something that does that for you. And the same logic applies to the PHP implementation: If you need to carry this state among with the icon, then create a wrapper class that contains the icon.

**Comment by mutec** [comment]
> Toggling `forceSolid` is unsafe, because you cannot make any assumptions about what they look like.

Since those icons are mostly set programatically (except those selected by `IconFormField`), one knows what it looks like when setting the parameter's value. So one could use that parameter explicitly if needed/wanted, but in case of `{icon name=$object->getIcon()}` there is no way to display the solid version.



> because whatever happens inside is not your business.

I assume you got me wrong. I don't want to manipulate the icon-tag itself (or it's content), but I want to wrap that (`toHtml()`) generated code inside another tag like:
`<a href="$url" class="button jsTooltip" title="$action">$icon <span class="invisible">$action</span></a>`
while `$icon` repesents `FontAwesomeIcon::toHtml()`

Btw. is there a wanted/best way to set the icon's color? In previous versions it was possible to use CSS-classes like `green`.
I'd wrap the icon in a `span`-tag using an id or class and do something like that:
```CSS
.greenIcon > fa-icon {
    color: green;
}
```
Is there an easier/better way to achieve that?

**Comment by dtdesign** [comment]
> So one could use that parameter explicitly if needed/wanted, but in case of `{icon name=$object->getIcon()}` there is no way to display the solid version.

That is correct, but not an actual problem. Icons set through the form field are a non-issue, because you cannot safely make assumptions about its content anyway, so you will have to take whatever is its value. For your programmatic icons there are two different approaches:

1. Create dedicated methods to return the desired icon. If you already have `getIconEnable(): FontAwesomeIcon`, you could also introduce `getIconDisable(): FontAwesomeIcon` and you’re done.
2. Use a simple `{if}` statement to generate different markup depending on the action. If you take a closer look at our current templates, this is exactly what we’ve done to generate different icons. On the bright side it makes templates much more cleaner and readable.


> I don't want to manipulate the icon-tag itself (or it's content), but I want to wrap

Nothing prevents you from _wrapping_ the icon. Just think about the `DatabaseObjectDecorator` implementations that achieve the same thing without every touching the original class.


> Is there an easier/better way to achieve that?

No and for a good reason: Color on its own is insufficient to transport a message.

Icons that represent a status must always carry a text explanation to inform users what they are meaning. This can either be text that appears adjacent to them or a title tag / tooltip that appears when hovering the element. This means that whenever you want to tint an icon you will need a wrapping element anyway that provides this information.

**Comment by mutec** [comment]
Since the class isn't even able to handle anything else than `regular` and `solid`, I'm going to copy the logic and implement everything I need in a dev-package.

**Comment by dtdesign** [comment]
> Since the class isn't even able to handle anything else than `regular` and `solid`, I'm going to copy the logic and implement everything I need in a dev-package.

Just fyi: This is by design, because you cannot reliable use any other styles. The icons are configured to try to use non-solid variants unless explicitly requested. This allows it to use any requested icon weight, but keep the semantics unchanged.

This has to do with the restrictions of the Font Awesome 6 licenses where they removed the theme licenses. Without this type of license you will have to license the usage of the font per seat (that is every customer of your software) on a yearly basis. Bundling their paid font in a product for sale is effectively illegal since FA6 unless you pay them royalty for every customer.

This was quite the awkward discovery when discussing this with their sales team, because we originally intended to ship their paid variants with our commercial software. 499$/yr plus 10$/yr/customer is quite a hard pill to swallow…

**Comment by mutec** [comment]
> This is by design, because you cannot reliable use any other styles.

I agree for the "pro"-styles, but the brand-stuff provided by the core itself should be reliable - even if it's a different type of integration, but it supports sizes too.
Reliability is fragile at all as the upgrade to FA 6 showed. Changing the stored icon-names is kind of awkward. I'm currently writing an util for mapping those icons based on your extra-script and doing some custom stuff. I thought about creating an issue for a log of missing icons earlier this day, so one could find and replace icons that aren't available any longer for whatever reason.

> This has to do with the restrictions of the Font Awesome 6 licenses where they removed the theme licenses. Without this type of license you will have to license the usage of the font per seat (that is every customer of your software) on a yearly basis. Bundling their paid font in a product for sale is effectively illegal since FA6 unless you pay them royalty for every customer.

I know. The only but uncool solution would be some kind of annual subscription for an additional package while the sales process is linked to the FA API and able to order/cancel seats in real-time. But even if that works there's the question, what happens after the cancellation? The icons might have been linked somewhere and are still stored on the customer's system…



> This was quite the awkward discovery when discussing this with their sales team, because we originally intended to ship their paid variants with our commercial software. 499$/yr plus 10$/yr/customer is quite a hard pill to swallow…

The main problem is the 499$/yr since the 10$/yr could be paid by the customer for the "integration-package" and depend on whether there are customers that are willing to pay for it. But those 499$ have to be paid anyway; it'y crazy, but the 99$/year + 20$/yr/customer would be the better option.

Btw. I don't get the sense of the following call. It returns a boolean, but the result is never used. Should that line call `validateName()` instead?
https://github.com/WoltLab/WCF/blob/8351436e4afb599a8a7dc7983597cf2f7bf474e1/wcfsetup/install/files/lib/system/style/FontAwesomeIcon.class.php#L92

**Comment by TimWolla** [comment]
> Should that line call validateName() instead?

I'd rather delegate to `fromValues()` instead to reduce the code duplication.
