### ISSUE TITLE
Notification to moderators when content has been reported

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#5281]

**Comment by dtdesign** [comment]
The main blocker is the lazy computation of the values in `wcf1_moderation_queue_to_user`.

This was introduced in WCF 2.0 with the intention to reduce the latency of actions that triggered an entry in the moderation queue. The primary motivation was the computational expensive check of the moderator permissions, because these can go down to a very granular level. While this works as expected, the downside is that it is unknown ahead of time which moderator is responsible for a specific queue entry.

However, the previous implementation in WCF 1.x was also uncached, so while we massively improved the performance, we were probably overshooting here. It should be feasible to determine the responsible users ahead of time in addition to the runtime/on demand checks which is necessary for new moderators being appointed. Once this has changed we are able to determine which users need to be notified of a new queue entry.

**Comment by Cyperghost** [comment]
The calculation of the moderators responsible for an entry could cause a performance problem.

For example, the following would have to be done for posts
- Search for all moderators of a forum
- Search for all moderators who are not explicitly entered in the forum.

For all these users it would then have to be checked whether

- the `mod.general.canUseModeration` permission is set
- the rights `canEnablePost` and `canDeletePost` are set in the respective forum.

The same applies to comments. The `IModerationQueueManager` calls functions of the `ICommentManager`. However, this also has no possibility to check the authorization of a user, but only checks the current user.
The following changes would have to be made here:
- The `canModerate` function would need an additional parameter `UserProfile`, which is used to check the authorization of an explicit user.

---
Alternatively, all users who have the `mod.general.canUseModeration` permission could always receive an entry in `wcf1_moderation_queue_to_user`, a few entries would be unnecessary, but would be automatically deleted again as soon as moderation is called or an attempt is made to send the notification later.

**Comment by dtdesign** [comment]
After thinking about it for some time, I come to the conclusion that the number of users wich access to the moderation panel should be fairly small, even for a larger site. We could run a database query to quickly identify the list of user ids that are part of such groups. For really large sites this still reasonably yield a high double digit number but that would still be perfectly fine.

Fetching the group ids for each user is going to be a bit painful, but those are still index reads plus the report lives on a dedicated request. If that particular request takes an extra second, that will still be an acceptable latency.

Have you tested the performance impact of fetching, say, 50 users and checking their permissions out of a large user base?

**Comment by dtdesign** [comment]
70ms is huge, have you checked what causes this issue? I’m guessing this is related to `User::getGroupIDs()`?

**Comment by dtdesign** [comment]
The latency of the permission cache builders are dependent whether or not their cache is stale which barely happens. In that case this is acceptable and significantly lower on runtime to the point where I expect sub 10ms latency for the entire check.

That said, we should continue implementing this, the performance implications are within reasonable bounds.
