### ISSUE TITLE
Implement `Component/Ckeditor.getEditor()`

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5325]
The `ClassicEditor`-object isn't accessible anywhere at the moment, which makes it impossible to interact with the editor-instance. Even a simple use-case like listening to changes isn't possible.

**Comment by dtdesign** [comment]
The `Ckeditor` component will be used to provide ready-to-use methods that take care of the interaction with the native API of the editor. Please let me know if there is something missing that you need and I will see what I can do. We will not expose the editor’s native API to the user-land.

**Comment by dtdesign** [comment]
Can you describe the use case behind the listening for changes? There is already the auto save feature that runs in periodic interval, but debounced, which could be a good starting point. Maybe there is a way to build something around this.

Image resizing is on our list for 6.0, but we’re focusing on stabilizing the integration of the existing features (= feature parity) before we tackle new features.

Custom buttons and button groups are already supported in the current build. What is that you are missing?

**Comment by mutec** [comment]
For testing purposes (the code-stuff is or was broken due to a DOM-Element mismatch) I wanted to dump the generated html to a textarea. I ended up dumping the code every 1000ms - causes a lot of unnecessary executions, but did it for the testing.

Oh, cool. However it was an example, I'm pretty sure you are not going to provide all possible plugins by default, are you?
Sadly I didn't have much time to test the new implementation yet, so it was just a quick "what could I do?".

**Comment by dtdesign** [comment]
> For testing purposes (the code-stuff is or was broken due to a DOM-Element mismatch) I wanted to dump the generated html to a textarea. I ended up dumping the code every 1000ms - causes a lot of unnecessary executions, but did it for the testing.

You can enable the debug mode and the developer tools. Next you can issue `Devtools.toggleEditorInspector()` in the console which will dynamically load and attach CKEditor’s own inspector. It has proven to be quite helpful for me to be able to look into the internals of the editor.


> However it was an example, I'm pretty sure you are not going to provide all possible plugins by default, are you?

No, but we’re looking to cover everything that has existed before and looking into expanding on top of that. For now, we keep the API surface as small as possible, which is a bit of a lesson we have learned the hard way with earlier editors.

That’s why it’s important to us to learn the different use cases and to provide a proper API for that. It allows us to both prevent unintentional API misuse as well as learning what features are important so that we can provide a stable API moving forward.

**Comment by mutec** [comment]
We still need access to that property in order to implement an WYSIWYG field supporting i18n.
Otherwise we'd have to copy paste the whole integration in order to implement a getter method for that property.

**Comment by dtdesign** [comment]
You can already create and inject your own editor plugins that can achieve whatever you need: https://docs.woltlab.com/6.0/javascript/components_ckeditor5/#creating-plugins

**Comment by dtdesign** [comment]
Actually, the data downcast is a very expensive operation that you really do not want to run whenever a change occurs. If you think that there is a bug in one of our components then please go ahead an file a report so we can fix the issue.

**Comment by mutec** [comment]
I opened #5712 for that.
