### ISSUE TITLE
Use `null` for empty object id in `DatabaseObject`

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5352]
Using `0` instead of `null` is quite confusing since `0` is a valid integer value. For me using `null` makes it clear, that the value is not set.

**Comment by TimWolla** [comment]
I don't see this happening ever. The benefit is nil to tiny, but this change would affect the vast majority of existing code. It's also effectively impossible to verify the correctness, because this would result in a silent behavioral change for common patterns (e.g. when using type-safe comparisons).

There _are_ issues with the design of the DBOs, this is not one of them. If we would perform a breaking change, it would make more sense to replace the entire ORM with some “off-the-shelf” solution (e.g. Doctrine).
