### ISSUE TITLE
Integrate dark mode SQL updates into the update instructions

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#5354]
This file needs to be run (as early as possible, because missing variables can brick the ACP):

https://github.com/WoltLab/WCF/blob/4e0dcf2698ace5426dd20ef5cec0a9043f44fca9/com.woltlab.wcf/update_com.woltlab.wcf_6.0.sql#L1

- [ ] However looking at the actual changes, I wonder if we also need SQL instructions to fill in the new `defaultValueDarkMode` column for all existing variables?
- [ ] Should this be transformed into an upgrade script instead of a bare SQL file? I tend to prefer actual scripts nowadays, because they are much more flexible.
- [ ] `wcfSidebarBorder` missing in the SQL file
- [ ] `wcfHeaderMenuDropdownBorder` missing in the SQL file

**Comment by dtdesign** [comment]
During the development of the dark mode I was at one point considering dropping the table altogether and moving the values into a static array. However, this felt a bit like a rabbit hole therefore I kept it as it is.

The new values will be applied as a series of `UPDATE` statements, therefore we can keep them in a SQL file for simplicity and because its idempotent. Using a script adds no value at this point.
