### ISSUE TITLE
Artificial 90d limit for paid subscriptions

### ISSUE THREAD

**Issue by Armynator** [WoltLab/WCF#5355]
I considered using the paid subscription feature in production lately, and noticed this:
https://github.com/WoltLab/WCF/blob/92dfd5e7df069a089f105f614311e758b5ba41b4/wcfsetup/install/files/lib/acp/form/PaidSubscriptionAddForm.class.php#L269-L271

Why are these artificial limits there? It makes no sense to me that days are limited to 90, months to 24 and years to 5. Especially the first limit is really weird, as it's a totally valid usecase to enter the desired subscription time in days imo.

To be more specific:
I understand why days, months and years are seperate units. They automatically calculate the actual duration, so 1 year is 364/365 days instead of 360 and 1 month is (28?)-31 days instead of 30. A bit weird (and probably overengineered), but fine.
The real issue I have is that something paid like this should have an absolute, totally foolproof duration instead of relying on dynamically calculated days because of ever changing year/months lengths. I mean it's there in theory, but artificially locked out because of the 90d limit. (I'm not asking for hours/minutes/seconds btw, that would be a bit overkill)

So.... is it safe to ignore and remove this check? Or am I missing something and is there a good reasoning behind the limits?

**Comment by dtdesign** [comment]
Understood. Looking through the code I don’t see an immediate reason for the limitations, this might be part of the API requirements, as the paid subscriptions use an older version of PayPal’s API.

You can try lifting this restriction yourself and see if it works. Otherwise please feel free to reach out to us through the ticket support and we’ll look into this.
