### ISSUE TITLE
Editing a style breaks colormode switcher

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#5376]
Debugmode on (color mode switcher does not work with debugmode off).

Add new style
Save style
Go to style overview
Activate new style
Edit new style
Add dark color scheme
Go to frontend
Switch color mode
-> Everything ist fine

Go to style overview
Edit new style
Save style
Go to frontend
Switch color mode
-> Switch is broken

Clear cache via ACP
Go to frontend
Switch color mode
-> Everything ist fine again

**Comment by TimWolla** [comment]
> Debugmode on (color mode switcher does not work with debugmode off).

That's because the minified JavaScript is not up to date (it's on the WoltLab Suite 5.5 state). It will be updated regularly beginning with the Alphas.

**Comment by SoftCreatR** [comment]
Refreshing the minified Javascript doesn't fix this issue.

**Comment by cls-design** [comment]
Looks like after saving a style the complete darkmode-part is missing in style-x.css:

![Bildschirmfoto 2023-04-06 um 13 02 40](https://user-images.githubusercontent.com/1590626/230359064-8c48466c-ba9f-410d-995f-e89f637de7b5.png)

**Comment by dtdesign** [comment]
It appears to be that the test compilation is the root cause of this issue. The test result is persisted to the disk in an effort to prevent compiling the style twice. However, this code path will only ever test one variant of the style, causing the result to be either “always light” or “always dark”.
