### ISSUE TITLE
Font Problem

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5400]
Dunno, if this is a problem with the specific font, or if this happens with multiple fonts. However, this worked fine in WSC > 6.0. In my specific case, the problem is the font `Nunito Sans`. The font is being downloaded fine, but the corresponding `font.css` won't be included. This leads to the use of the fallback font (Segoe UI in my case).

However, changing the font to something else (e.g. Open Sans) works as expected.

**Comment by TimWolla** [comment]
The cause is this call here:

https://github.com/WoltLab/WCF/blob/14db55719787ebb899153abd250c9aff449d8991/wcfsetup/install/files/lib/system/style/StyleCompiler.class.php#L159

It causes the Google font to be surrounded by quote here:

https://github.com/WoltLab/WCF/blob/14db55719787ebb899153abd250c9aff449d8991/wcfsetup/install/files/lib/system/style/StyleCompiler.class.php#L603

Which then fails to find the directory for `font.css`.
