### ISSUE TITLE
[6.0] Display errors in stats

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5471]
![image](https://user-images.githubusercontent.com/81188/236004022-8a4a453f-9c05-4f45-a14d-149fe9f9d908.png)

The language variables exist.

**Comment by TimWolla** [comment]
Thanks.

> The language variables exist.

Probably no longer exposed to the JS. But this should just use the Intl API for number formatting where the phrase is no longer required.

**Comment by SoftCreatR** [comment]
For some reason, i don't think, that this is enough. What about decimal point for example?

**Comment by TimWolla** [comment]
> What about decimal point for example?

Intl will handle that correctly:

```
(1234567890.123456).toLocaleString('de-DE');
'1.234.567.890,123'
(1234567890.123456).toLocaleString('de-CH');
'1’234’567’890.123'
(1234567890.123456).toLocaleString('en-US');
'1,234,567,890.123'
(1234567890.123456).toLocaleString('en-IN');
'1,23,45,67,890.123'
```

See also: https://docs.woltlab.com/6.0/migration/wsc55/php/#internationalization (though that refers to the PHP counterpart).

**Comment by SoftCreatR** [comment]
I'll check that, and report back :)

**Comment by TimWolla** [comment]
Correctly understanding locales is literally the only purpose of [`.toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString). It's in the name.

For best results I recommend you to select locales for the installed languages in LanguageEditForm. For example by choosing English (United Kingdom) you get a 24h clock, instead of the 12h clock as used in the United States.

**Comment by SoftCreatR** [comment]
I understood that. But still. I was referring to `formatNumeric()`, that still uses `WCF.Language.get('wcf.global.decimalPoint')` instead of Intl. And I was right:

![image](https://user-images.githubusercontent.com/81188/236177586-735d949d-2099-451f-9794-4b12facfd4de.png)
