### ISSUE TITLE
Support custom item-layout in user menus

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5517]
Instead of the fixed properties it should be possible to pass some HTML for custom integrations. This could be easily done by checking whether a `template`-property exists or fallback to the current/default implementation if not.

![image](https://github.com/WoltLab/WCF/assets/1749344/8c85ac7d-4c81-4362-a375-ab66d7f4a78f)

**Comment by dtdesign** [comment]
This is not what I meant: You did not implement a user menu item provider, because it works the same as the others, you picked it because it shows the general behavior and positioning you would like to achieve.

For comparison, you wouldn’t treat a screw as a nail, just because it has a similar shame, would you? Yet, here we are and you try to shove your shopping cart into an existing UI component that really is neither designed nor intended for what you would like to accomplish.

What makes it worse is that even if we somehow make it possible for you to cram the shopping cart in there, it would make for a poor experience on mobile. The indicators are built around the unread logic that you have to completely bypass (this should have been a sign that you’re going in the wrong direction though!) which makes the shopping cart pretty hidden.

Have you considered simulating a legacy panel item instead? As long as the item satisfies the API expectations defined in https://github.com/WoltLab/WCF/blob/62b42b362b749c86cc77ceab48ef79ed09cbed57/ts/WoltLabSuite/Core/Ui/Page/Menu/User.ts#L33-L38 you are pretty much free to do whatever you like. You should be able to build a similar DOM, allowing you to inherit all the styling and then make adjustments where you need it. Plus you get to bypass all the components (unread tracking, time, etc.) that you don’t want.

**Comment by mutec** [comment]
Sound's good. Is that "legacy"-part meant to stay or will it be removed in future builds? It wouldn't make much sense to use it in case it's going to be removed in e.g. 6.2. In that case it would make sense to write an own implementation, maybe bringing the cart-icon at top level next to the search-button in the mobile view.

**Comment by dtdesign** [comment]
The legacy part is meant to be removed at some point, yes. However, while I do not want to water down the implementation of the user menu providers, I am open to implement this as a separate, permanent solution. This would allows us to eventually remove the jQuery implementation while still permitting your custom implementation.

My suggestion at this point is that you poke around with the legacy feature, make use of the existing reference DOM for the new user menu items and then report back with how far you got. The CSS grids should make it easy for you to customize individual bits, while still using most of the existing CSS. I can even imagine implementing a proper API interface that allows your implementation to report a “Please show an indicator on mobile” without making any assumption about what it means.

**Comment by dtdesign** [comment]
@mutec Have you been able to make any progress so far and/or did you run into any shortcomings that we need to address?

**Comment by mutec** [comment]
Is there a specific point where/when to add the event listener? I called this script within the template for the element but it seams to be too late or whatever:
```JS
export function test(): void {
	console.log("test1!");
	EventHandler.add("com.woltlab.wcf.pageMenu", "legacyMenu", (blob) => {
		console.log("test2!");
	});
}
```
`test2` is never displayed, but `test1` is.

**Comment by mutec** [comment]
That doesn't seam to fit the needs, I think I have to write a completely new cloned integration.

**Comment by dtdesign** [comment]
That doesn’t sound right, because the legacy implementation was heavily tested during implementation. For example, you can (with some adjustments) install the conversation system in version 5.4 and the user panel item will still work.

The menu itself is lazily constructed on first call, which means that the event is present at that time. Are you able to provide a working code that helps illustrate where the problem lies?

**Comment by dtdesign** [comment]
@mutec Have you been able to make some progress here?
