### ISSUE TITLE
Author only search

### ISSUE THREAD

**Issue by SoftCreatR** [WoltLab/WCF#5544]
Since 6.0, you cannot longer search for all contents by a particular author, because `q` is a required field now.

![image](https://github.com/WoltLab/WCF/assets/81188/3fb59ea5-5676-4743-b61d-0eb6ca4531b0)

**Comment by dtdesign** [comment]
The search feature is incapable of accurately representing all contents of an editor because results will be cut off at 1,000 items. The user profile already offers dedicated quick links to find the content of a particular author by type, for example, finding all posts or threads of a user. These quick links are not built on top of the search and therefore are able to represent the data regardless of the size of records.

The search was always designed with a search term in mind and suffered from a couple of issues when used without one. Being able to run a search without a term existed for historical reasons as it was serving as a substitute for the lack of quick filters that did not exist back then.

**Comment by SoftCreatR** [comment]
I understand your reasons, but it's somewhat inconvenient because now you have to (especially as a user) find the user whose content you want to search for in order to access their profile and then search for the content there. This becomes even more difficult if the user has restricted access to their profile.

**Comment by dtdesign** [comment]
> […] now you have to (especially as a user) find the user whose content you want to search for in order to access their profile and then search for the content there.

I’m sorry, but I do not think this holds up. You don’t wake up one morning and decide to search for content of <random user 123>, but instead come across content of that user. You can then simply click on the username to access their profile.


> This becomes even more difficult if the user has restricted access to their profile.

No, it doesn’t. Restricting the profile does not prevent the access to the quick links to find their content.
