### ISSUE TITLE
Overhaul the UX of the authentication process

### ISSUE THREAD

**Issue by BurntimeX** [WoltLab/WCF#5695]
All pages and forms that are part of the login and registration process should use a simplified layout/template that is different from the rest of the pages and where the form is the main focus.

We could omit the main menu, the user panel and the breadcrumbs.

<img width="1062" alt="Bildschirmfoto 2023-10-25 um 16 41 01" src="https://github.com/WoltLab/WCF/assets/915475/d134a405-6c8d-44d8-b143-64b62562b20f">

### Login Form
- [x]  Inputs for username/email+password
- [x]  Link to "Forgot Password?" form
- [x]  Link to Registration form
- [x]  Buttons for 3rd party logins

### Registration Form
- [x]  Skip disclaimer page and display an "Accept Terms" checkbox in the form instead.
- [x]  Remove inputs for "confirm email" and "confirm password".
- [x]  Overall make it more compact / remove the number of sections.
- [x] Link to Login form
- [x]  Buttons for 3rd party registration
- [x] Don't use a section for the reCaptcha

### Header
- [x] Separate links/buttons for login and register

**Comment by eveneme** [comment]
You can also center the logo.

**Comment by eveneme** [comment]
What do you think about adding the input name in input like in the photo? It would also save space.

![image](https://github.com/WoltLab/WCF/assets/85762221/6fcaff45-002e-4464-8156-b9146d4b6576)

**Comment by cadeyrn** [comment]
> We could omit the main menu, the user panel and the breadcrumbs.

I don't agree that it should be made harder for users to reach other sites just because you're on the registration or login page. Especially, the main menu may contain important links that should be accessible from anywhere.

**Comment by eveneme** [comment]
> > We could omit the main menu, the user panel and the breadcrumbs.
> 
> I don't agree that it should be made harder for users to reach other sites just because you're on the registration or login page. Especially, the main menu may contain important links that should be accessible from anywhere. Also, I can't see any advantage of using a different look and feel for these pages.

On the login or registration page, links to other pages are not necessary because these pages serve different purposes. Why do you need a menu on the login page? You can simply click on the logo, and it will take you to the homepage. Take a look at the login or registration pages of Facebook, Twitter, and so on. They usually have a well-organized UI/UX design.

**Comment by cadeyrn** [comment]
> On the login or registration page, links to other pages are not necessary

You can only talk about your platform. You are not in a position to tell me what I think is necessary for my platforms. And even if it's not necessary, it still doesn't mean that there is any advantage in removing primary navigation elements. On the contrary, I even find it confusing from the user's POV when the interface changes in such a radical way on only these two pages.

> Why do you need a menu on the login page?

Why do you need it on page X or page Y? You can ask exactly the same question for every other page. It makes no sense to ask this only for the login page and not for others.

> Take a look at the login or registration pages of Facebook, Twitter, and so on

I won't compare Facebook or X (it's no longer called Twitter) with my WoltLab Suite based platforms because these are totally different things with different UX requirements. X is not even accessible as guest at all, so there is no point in this comparison.

> They usually have a well-organized UI/UX design.

Some say so, others say so. Not everyone will agree with you on that point. I don't want to take sides, but I would like to point out that there is also a lot of criticism on these platforms regarding certain UX aspects. They don't have Apple's reputation for UX, and even they aren't perfect at everything. So "Facebook is doing this, therefore it has to be great UX" is not a very strong argument for me.

**Comment by eveneme** [comment]
I see, you're talking about yourself and your platforms. The convenience of registration and login is designed for the general public, not for individual preferences. It's known that everyone has their own tastes. I provided the examples of Facebook and Twitter because masses of people visit them daily, and they had to ensure a well-organized UI/UX for login and registration to make it clear and readable for the majority, not for individual preferences.

**Comment by eveneme** [comment]
my suggestion 

Login:
![image](https://github.com/WoltLab/WCF/assets/85762221/f84c8a4c-a525-4885-8b4e-c3cf3b68de09)

Register:
![image](https://github.com/WoltLab/WCF/assets/85762221/e2d88c8e-7a95-4d5a-a581-3470a5caab27)

**Comment by eveneme** [comment]
my suggestion V2

Login:
![image](https://github.com/WoltLab/WCF/assets/85762221/ff1e8307-da8a-4cf8-8fc6-1afe0279f565)

Register:
![image](https://github.com/WoltLab/WCF/assets/85762221/b6a2950c-fbb0-4595-8235-495c7393cbff)

**Comment by eveneme** [comment]
my suggestion V3

Login:
![image](https://github.com/WoltLab/WCF/assets/85762221/6bb2a5d2-c104-43dc-bac9-6d976d797ec9)

Register:
![image](https://github.com/WoltLab/WCF/assets/85762221/b4d17836-ffb1-4052-94df-00d2dd683f4d)

**Comment by eveneme** [comment]
my suggestion V4

Login:
![image](https://github.com/WoltLab/WCF/assets/85762221/3d62b8ff-cfef-4495-8ed9-28177d15b50e)

Register:
![image](https://github.com/WoltLab/WCF/assets/85762221/6ee437cb-8c63-4ce7-9119-bf75cfb9ef1a)

**Comment by eveneme** [comment]
My suggestion V5

![image](https://github.com/WoltLab/WCF/assets/85762221/00153459-1aa1-4b95-9baf-04b6e75c35a9)

![image](https://github.com/WoltLab/WCF/assets/85762221/dc9b76fa-12b0-489f-8055-011c73c52c3f)

![image](https://github.com/WoltLab/WCF/assets/85762221/2a5147c4-69eb-4fe4-99f1-37be8aa4fae0)

![image](https://github.com/WoltLab/WCF/assets/85762221/2ad08deb-a86b-405e-a4bf-b93ca9b1316f)

**Comment by eveneme** [comment]
V6
![image](https://github.com/WoltLab/WCF/assets/85762221/0701723c-68eb-4bf4-b832-427dcfa16138)

**Comment by eveneme** [comment]
I would enlarge the login button and add the 'remember me' option.

**Comment by BurntimeX** [comment]
What do you mean by "Enlarge the login button"?

There is no "remember me" option in our software. Sessions are always valid for a longer period of time.
