### ISSUE TITLE
Open Graph - upload a photo via the administration panel

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#5722]
The ability to upload Open Graph images via the administrative panel. Currently, it is only possible to paste a link to the image, which makes the task a bit more cumbersome because you have to upload the image to the server first. Enabling image uploads through the administrative panel would streamline this process.

**Comment by dtdesign** [comment]
We’ve looked into this and there is no proper path forward because of how these options are implemented from a technical point of view. The current implementation is much more in complex in terms of what it permits, including but not limited to external images, relative paths and others. Changing this to an upload is much more complex due to house-keeping, cache busting and all other sorts of logic due to the path previously being unmanaged.

There is a point at which we will overhaul the way options are implemented and I can imagine this field eventually becoming an “upload only” field but this is still quite far in the future. There are already some inconsistencies with file uploads in the options and we rather unify them all at once.
