### ISSUE TITLE
Clearing, simplifying the main view, relocating buttons.

### ISSUE THREAD

**Issue by eveneme** [WoltLab/WCF#6012]
Hi, in my opinion, buttons like "Mark all as read," the RSS Feed button, and the ignore board button should be moved to the user profile menu. This would create a cleaner interface without unnecessary buttons on the main page, as shown in the example below. Of course, I'm referring to the main page of the forum.
Mobile:

Before:
![Zrzut ekranu 2024-10-09 135448](https://github.com/user-attachments/assets/e3d6831e-7ec2-4392-9753-a8729d445b4c)

After:
![Zrzut ekranu 2024-10-09 135439](https://github.com/user-attachments/assets/eeecb8fa-5c60-4029-993d-6f6169193dd6)

Desktop:

Before:
![Zrzut ekranu 2024-10-09 135412](https://github.com/user-attachments/assets/0754a5ef-f8ba-4044-a13b-d26a36264de2)

After:
![Zrzut ekranu 2024-10-09 135430](https://github.com/user-attachments/assets/fccc1d2d-574e-4a95-863f-73ff19ea7e2d)

**Comment by dtdesign** [comment]
The buttons were intentionally moved to this exact position to make them more available regardless of the type of device. Previously those were tiny icons next to the breadcrumbs on desktop and placed in the menu for mobile users. Many years have shown that these were poorly discovered by users which is why we moved them.
