### ISSUE TITLE
The position of the search is not always calculated correctly

### ISSUE THREAD

**Issue by cls-design** [WoltLab/WCF#6062]
While the position of the user panel menus is always calculated correctly, this is not always the case with the search.

For example, in the style the search is calculated as follows:

50px 219px auto auto

![Bildschirmfoto 2024-11-12 um 11 18 41](https://github.com/user-attachments/assets/131f9c73-555d-4748-b9e3-57df47604ab8)

219px is the distance between the search icon and the edge of the screen and instead of using zero, the distance to the edge is added. If I change the value to negative, the search is moved to the edge:

![Bildschirmfoto 2024-11-12 um 11 22 07](https://github.com/user-attachments/assets/cb219f99-bdcd-4690-b446-a8813d053622)

if I enter a zero, the horizontal position is correct again:

![Bildschirmfoto 2024-11-12 um 11 22 24](https://github.com/user-attachments/assets/86461023-9844-4972-84e8-254addbae86f)

The distance from the top is also not correct in this case. I have noticed that if I change the viewport manually, the position from above is corrected:

![Bildschirmfoto 2024-11-12 um 11 23 09](https://github.com/user-attachments/assets/1ddc523c-b944-428a-96d7-313ed4713329)

Would it be possible to adopt the positioning of the user menus for the search as well?

**Comment by dtdesign** [comment]
@cls-design The position is dynamically calculated based on the position of the reference element. This appears to be a problem specific to that style (or to be precise: the style’s CSS) that causes the calculation to be off.

Please feel free to contact us by ticket if this is a proprietary style, otherwise please provide a source where the style can be obtained from w/o requiring a login.

**Comment by cls-design** [comment]
I don't know what exactly the desired functionality of the search panel is. Based on the curves of the buttons, I assume that the search should open under the search panel in the same way as the user menus?

For example:

```
@include screen-lg {
	#pageHeader {
		display: flex;
		flex-direction: column;
		#pageHeaderPanel {
			order: 2;
		}
		#pageHeaderFacade {
			order: 1;
		}		
	}
	.pageHeaderContainer {
		padding-top: 0;
	}
	.pageHeaderPanel {
		position: relative;
	}	
}
```

When I open the search, it opens with top 50px. Is this the intended position that the search always opens with top 50px? If I change the viewport manually, it jumps back under the search button:

![Bildschirmfoto 2024-12-02 um 16 51 43](https://github.com/user-attachments/assets/7c0764c9-fc30-44b4-8f6d-7daf369bb452)

This actually seems more like the right position to me?

----
Edit:

See the default style "WoltLab Suite"

https://cls-design-demo.com/

**Comment by dtdesign** [comment]
Thank you for the instructions, that was incredibly helpful. I reviewed the code and it currently expected the `.pageHeaderPanel` to be sticky and consequently aligns it by using its computed height. This is a limitation of the current implementation and will not be changed for compatibility reasons.

There is a larger effort to overhaul the style system and you’re more than welcome to comment on these issues and to suggest further improvements: #6028

A workaround for your issue is to overrule the top position using `!important` with a value that matches your updated position.

**Comment by cls-design** [comment]
Thanks for looking at it. The problem with position-top is that I don't know how big the logo will be at the end and so a dynamic header height is not possible (a dynamic solution can be achieved e.g. with a CSS grid). For a future version it would be great if the search would always open in the right place below the search-button.

Edit:

I will make a suggestion for the search
